name       : python-editor
version    : 1.0.4
release    : 6
source     :
    - https://pypi.io/packages/source/p/python-editor/python-editor-1.0.4.tar.gz : 51fda6bcc5ddbbb7063b2af7509e43bd84bfc32a4ff71349ec7847713882327b
license    : Apache-2.0
component  : programming.python
summary    : Programmatically open an editor, capture the result.
description: |
    python-editor is a library that provides the editor module for programmatically interfacing with your system's $EDITOR.
build      : |
    %python3_setup
install    : |
    %python3_install
